MESSAGE (" find clapack ")
if(WIN32)
	SET (LAPACK_ROOT "D:/usr/CLAPACK")
	IF(EXISTS D:/usr/CLAPACK_14)
		SET (LAPACK_ROOT "D:/usr/CLAPACK_14")
	ENDIF()
    include_directories (${LAPACK_ROOT}/include)
    set(BLAS_LIBRARY ${LAPACK_ROOT}/lib/blas.lib)
	set(LAPACK_LIBRARY ${LAPACK_ROOT}/lib/lapack.lib)
    set(F2C_LIBRARY ${LAPACK_ROOT}/lib/libf2c.lib)

elseif(APPLE)
	set(F2C_LIBRARY libf2c.a)
	set(BLAS_LIBRARY libblas.a)
	set(LAPACK_LIBRARY liblapack.a)
elseif (UNIX)
include_directories (/usr/local/include)
	set(F2C_LIBRARY /usr/local/lib/libf2c.so)
    set(BLAS_LIBRARY /usr/local/lib/libblas.so)
	set(LAPACK_LIBRARY /usr/local/lib/liblapack.so)
	
endif()

message (" blas is " ${BLAS_LIBRARY})
message (" lapack is " ${LAPACK_LIBRARY})
message (" f2c is " ${F2C_LIBRARY})
