MESSAGE (" find hdf5 ")
SET (INSTALLED_HDF5 OFF)
if (WIN32)
    IF (EXISTS "D:/usr/hdf5-1.8.21-s")
        SET (HDF5_INCLUDE_DIRS D:/usr/hdf5-1.8.21-s/include)
        SET (HDF5_LIBRARIES "D:/usr/hdf5-1.8.21-s/lib/libhdf5.lib")
    ELSEIF (EXISTS "D:/usr/hdf5-1.8.20-s")
        SET (HDF5_INCLUDE_DIRS D:/usr/hdf5-1.8.20-s/include)
        SET (HDF5_LIBRARIES "D:/usr/hdf5-1.8.20-s/lib/libhdf5.lib")
	ELSEIF (EXISTS "C:/Program Files/HDF5/cmake/hdf5")
# location of configure file FindHDF5.cmake
		SET (HDF5_DIR "C:/Program Files/HDF5/cmake/hdf5")
        SET (INSTALLED_HDF5 ON)
    ELSEIF (EXISTS "D:/usr/hdf51820")
        SET (HDF5_INCLUDE_DIRS "D:/usr/hdf51820/include")
        SET (HDF5_LIBRARIES "D:/usr/hdf51820/lib/hdf5.lib")
    ELSEIF (EXISTS "D:/usr/hdf5")
        SET (HDF5_INCLUDE_DIRS "D:/usr/hdf5/include")
        SET (HDF5_LIBRARIES "D:/usr/hdf5/lib/hdf5.lib")
	ENDIF ()
ELSEIF (APPLE)
	SET (INSTALLED_HDF5 ON)
ELSEIF (UNIX)
	SET (HDF5_VERSION "1.8.18")
	SET (HDF5_INCLUDE_DIRS "/home/td21/usr/hdf5/include")
        SET (HDF5_LIBRARIES "/home/td21/usr/hdf5/lib/libhdf5-shared.so")

endif ()

IF (INSTALLED_HDF5)
FIND_PACKAGE (HDF5 REQUIRED)
ENDIF ()

MESSAGE (" hdf5 version is " ${HDF5_VERSION} )
MESSAGE (" hdf5 include is " ${HDF5_INCLUDE_DIRS} )
MESSAGE (" hdf5 library is " ${HDF5_LIBRARIES} )

include_directories (${HDF5_INCLUDE_DIRS})

MESSAGE ("Use Static HDF5")
##ADD_DEFINITIONS (-DH5_BUILT_AS_DYNAMIC_LIB)
